# Server
# ------

url:          http://zdroid.github.io
baseurl:
encoding:     UTF-8
exclude:
  - README.md

# Dependencies
# ------------

markdown:     kramdown

# Permalinks
# ----------

permalink:    pretty

# Meta data
# ---------

title:        ZDroid
author:       Zlatan Vasović
description:  Personal site of young designer and developer, Zlatan Vasović.
keywords:     zdroid, github, design, designer, development, developer
language:     en

# Links
# -----

blog:         http://zdroid.roon.io
twitter:      zdr0id
github:       ZDroid
instagram:    zdr0id
