# Server
# ------

encoding:     UTF-8
url:          http://zdroid.github.io
baseurl:      # empty
permalink:    pretty
exclude:
  - README.md

# Defaults
# --------

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Meta data
# ---------

title:        ZDroid
author:       Zlatan Vasović
description:  Personal site of young designer and developer, Zlatan Vasović.
keywords:     zdroid, github, design, designer, development, developer, code
language:     en

# Links
# -----

blog:         http://zdroid.roon.io
twitter:      zdr0id
_github:      ZDroid # `site.github` is used by GitHub pages
instagram:    zdr0id
